"""initial_schema

Revision ID: aca32761bee4
Revises: 
Create Date: 2026-08-31 15:47:20.895315+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca32761bee4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airfare_index_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.Column('baseline_period', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airfare_index_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airfare_index_values_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_airfare_index_values_frequency'), ['frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_airfare_index_values_id'), ['id'], unique=False)

    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_ota', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airlines_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_airlines_id'), ['id'], unique=False)

    op.create_table('dgca_reference_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('origin_code', sa.String(length=3), nullable=False),
    sa.Column('destination_code', sa.String(length=3), nullable=False),
    sa.Column('avg_fare', sa.Float(), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dgca_reference_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dgca_reference_data_destination_code'), ['destination_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dgca_reference_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dgca_reference_data_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_dgca_reference_data_origin_code'), ['origin_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dgca_reference_data_year'), ['year'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_code', sa.String(length=3), nullable=False),
    sa.Column('destination_code', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('dgca_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_destination_code'), ['destination_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_origin_code'), ['origin_code'], unique=False)

    op.create_table('scraping_job_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_scraped', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraping_job_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraping_job_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraping_job_logs_source_name'), ['source_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_scraping_job_logs_status'), ['status'], unique=False)

    op.create_table('raw_airfare_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=30), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advance_window_days', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('taxes_fees', sa.Float(), nullable=False),
    sa.Column('total_fare', sa.Float(), nullable=False),
    sa.Column('cabin_class', sa.String(length=30), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['airlines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_airfare_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_advance_window_days'), ['advance_window_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_departure_datetime'), ['departure_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_flight_number'), ['flight_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_airfare_quotes_total_fare'), ['total_fare'], unique=False)

    op.create_table('processed_airfare_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_quote_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('advance_window_days', sa.Integer(), nullable=False),
    sa.Column('clean_total_fare', sa.Float(), nullable=False),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_quote_id'], ['raw_airfare_quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_airfare_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_advance_window_days'), ['advance_window_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_clean_total_fare'), ['clean_total_fare'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_is_outlier'), ['is_outlier'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_processed_at'), ['processed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_raw_quote_id'), ['raw_quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_airfare_quotes_route_id'), ['route_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_airfare_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_route_id'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_raw_quote_id'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_processed_at'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_is_outlier'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_id'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_clean_total_fare'))
        batch_op.drop_index(batch_op.f('ix_processed_airfare_quotes_advance_window_days'))

    op.drop_table('processed_airfare_quotes')
    with op.batch_alter_table('raw_airfare_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_total_fare'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_route_id'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_id'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_flight_number'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_departure_datetime'))
        batch_op.drop_index(batch_op.f('ix_raw_airfare_quotes_advance_window_days'))

    op.drop_table('raw_airfare_quotes')
    with op.batch_alter_table('scraping_job_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraping_job_logs_status'))
        batch_op.drop_index(batch_op.f('ix_scraping_job_logs_source_name'))
        batch_op.drop_index(batch_op.f('ix_scraping_job_logs_id'))

    op.drop_table('scraping_job_logs')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_origin_code'))
        batch_op.drop_index(batch_op.f('ix_routes_id'))
        batch_op.drop_index(batch_op.f('ix_routes_destination_code'))

    op.drop_table('routes')
    with op.batch_alter_table('dgca_reference_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dgca_reference_data_year'))
        batch_op.drop_index(batch_op.f('ix_dgca_reference_data_origin_code'))
        batch_op.drop_index(batch_op.f('ix_dgca_reference_data_month'))
        batch_op.drop_index(batch_op.f('ix_dgca_reference_data_id'))
        batch_op.drop_index(batch_op.f('ix_dgca_reference_data_destination_code'))

    op.drop_table('dgca_reference_data')
    with op.batch_alter_table('airlines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airlines_id'))
        batch_op.drop_index(batch_op.f('ix_airlines_code'))

    op.drop_table('airlines')
    with op.batch_alter_table('airfare_index_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airfare_index_values_id'))
        batch_op.drop_index(batch_op.f('ix_airfare_index_values_frequency'))
        batch_op.drop_index(batch_op.f('ix_airfare_index_values_date'))

    op.drop_table('airfare_index_values')
    # ### end Alembic commands ###
